let suggestions = [
        "Mobile Legend",
        "Free Fire",
        "PUBG MOBILE",
        "DOMINO",
        "GENSHIN IMPACT",
        "POINT BLANK",
        "STUMBLE GUYS",
        "LEAGUE OF LEGENDS",
        "VALORANT",
        "CALL OF DUTY",
        "ARENA OF VALOR",
        "HONKAI IMPACT 3",
        "DRAGON RAJA",
        "SAUSAGE MAN",
        "ROGNAROK M",
        "LIFE AFTER",
        "LORDS MOBILE",
        "TOM AND JERRY",
        "LIGHT OF THEL",
];